refactor chm_diags and het_diags
eagles-project/e3sm_mam4_refactor pull request #119
Opened 2023-06-16 19:13 UTC by tangshuaiqi

1. remove unused code related to unused species
2. rename some variables to more meaningful
3. change the way of calculating tropospheric and stratospheric ozone
4. some other regular refactoring.

as the two subroutines are for diagnostics with many outfld calls. I have run long-term test to make sure outfld test also passed:

comp_testall_mo_chm_diags_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

2023-06-20 18:54 UTC, singhbalwinder requested changes
Looks good! These routines are computing just the diagnostics, so nothing much to do here. I liked the way you have changed variable names and named them appropriately.  Left some very minor comments.

2023-06-20 18:54 UTC, singhbalwinder commented on components/eam/src/chemistry/mozart/mo_chm_diags.F90
> +    integer     :: icol,kk, mm, nn
I think we can get rid of all `#if defs` for `MODAL_AERO`

2023-06-20 18:54 UTC, singhbalwinder commented on components/eam/src/chemistry/mozart/mo_chm_diags.F90
> +    integer     :: icol,kk, mm, nn
`rxn_rates` and  `invariants` are not used here

2023-06-20 18:54 UTC, singhbalwinder commented on components/eam/src/chemistry/mozart/mo_chm_diags.F90
> +    integer     :: plat
plat is never used

2023-06-20 18:54 UTC, singhbalwinder commented on components/eam/src/chemistry/mozart/mo_chm_diags.F90
> +    integer  :: plat
plat is never used here

2023-06-21 00:31 UTC, tangshuaiqi commented
@singhbalwinder all comments have been addressed. I also removed unused variables and indices in the module variables and in chm_diags_init.

2023-06-21 04:09 UTC, tangshuaiqi commented
All tests passed:
comp_testall_mo_chm_diags_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

2023-06-30 22:47 UTC, singhbalwinder approved these changes
This is ready to go! Thanks @tangshuaiqi !

2023-07-01 05:43 UTC, merged