create yaml testing files for subroutines in mo_photos
eagles-project/e3sm_mam4_refactor pull request #135
Opened 2023-07-23 20:54 UTC by tangshuaiqi

2023-07-24 15:08 UTC, jeff-cohere approved these changes
Thanks!

2023-07-24 15:16 UTC, mingxuanwupnnl requested changes
Looks good to me. There is a merge conflict to be resolved.

2023-07-24 20:04 UTC, brigaudet commented on components/eam/src/chemistry/yaml/mo_photo/f90_yaml/cloud_mod_end_yml.f90
> +
Should the following section be commented out to prevent side effect issues with the printouts?

2023-07-24 22:02 UTC, singhbalwinder approved these changes
Looks great! Like @brigaudet mentioned, those printout lines should be commented out.

2023-07-26 00:03 UTC, tangshuaiqi commented
All tests passed and conflict solved. @mingxuanwupnnl please check and approve if there is no problem.

comp_testall_yaml_mo_photo_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

2023-07-27 15:20 UTC, mingxuanwupnnl approved these changes

2023-07-27 15:21 UTC, mingxuanwupnnl commented
Looks good to me. Thank you.

2023-07-28 19:57 UTC, merged