YAML: create yaml testing files for subroutines in modal_aer_opt
eagles-project/e3sm_mam4_refactor pull request #156
Opened 2023-09-20 17:40 UTC by tangshuaiqi

creating yaml files for subroutines in modal_aer_opt.F90. Some module variables and diagnostics variables are included besides the in/out variables. There are a few 3-d or 5-d arrays, which are reshaped into a 1-d array and written out. The FORTRAN buildin reshape function has a default natural order of permutation from 1 to n.

2023-09-20 18:02 UTC, jeff-cohere approved these changes
Thanks!

2023-09-20 18:51 UTC, singhbalwinder approved these changes
Thanks, @tangshuaiqi !

2023-09-20 22:23 UTC, odiazib requested changes
It looks great! I just asked to add a few variables.

2023-09-20 22:23 UTC, odiazib commented on components/eam/src/chemistry/yaml/modal_aer_opt/f90_yaml/calc_refin_complex_beg_yml.f90
> +
please add  [crefwlw](https://github.com/eagles-project/e3sm_mam4_refactor/blob/966023e8429c1f913df38743dc84a1ab9911406b/components/eam/src/physics/cam/modal_aer_opt.F90#L1201C11-L1201C11) and [crefwsw](https://github.com/eagles-project/e3sm_mam4_refactor/blob/966023e8429c1f913df38743dc84a1ab9911406b/components/eam/src/physics/cam/modal_aer_opt.F90#L1204C56-L1204C63)

2023-09-20 22:23 UTC, odiazib commented on components/eam/src/chemistry/yaml/modal_aer_opt/f90_yaml/modal_aero_lw_beg_yml.f90
> +        call write_var(unit_input,unit_output,'cldn',cldn(yaml%col_print,:))
please add: `refrtablw`, `refitablw`, and `specrefndxlw`; [see here](https://github.com/eagles-project/e3sm_mam4_refactor/blob/966023e8429c1f913df38743dc84a1ab9911406b/components/eam/src/physics/cam/modal_aer_opt.F90#L32)

2023-09-20 23:18 UTC, tangshuaiqi commented
@odiazib Done. and added a few more module variables that may be needed in the subroutines.

2023-09-20 23:25 UTC, odiazib approved these changes
Thanks!

2023-09-21 22:50 UTC, tangshuaiqi commented
all tests passed. merge into maint

comp_testall_yaml_opt_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

2023-09-21 22:50 UTC, merged