Create yaml input output for subroutines in mo_drydep.F90
eagles-project/e3sm_mam4_refactor pull request #165
Opened 2023-10-26 17:37 UTC by mingxuanwupnnl

2023-10-27 19:02 UTC, tangshuaiqi requested changes
Just have a few comments on clean up the original code.

2023-10-27 19:02 UTC, tangshuaiqi commented on components/eam/src/chemistry/mozart/mo_drydep.F90
> +    use yaml_input_file_io
This should already be included in `common_uses.ymlf90`.

2023-10-27 19:04 UTC, tangshuaiqi approved these changes

2023-10-30 14:56 UTC, jeff-cohere approved these changes

2023-10-30 16:40 UTC, mingxuanwupnnl commented
@jeff-cohere I just saw your discussion with @brigaudet for string output. Would you suggest the same for `calculate_gas_drydep_vlc_and_flux` as well? You take a note about the string array, I then delete it from yaml and py files? Thank you

2023-10-30 16:47 UTC, jeff-cohere commented
Thanks for the note, @mingxuanwupnnl . I see that you're writing out `solsym` in a similar way, with everything already quoted. I think it's okay to leave things in since they're already properly quoted (especially if these arrays change between tests). The quoted strings don't hurt anything, and they actually are informative for testing purposes. But I can go either way in this case.

2023-11-15 17:26 UTC, singhbalwinder approved these changes
Looks good! In the final cleanup, please address @tangshuaiqi 's comment as well.

2023-11-23 03:43 UTC, mingxuanwupnnl commented
Final cleanup done. All tests passed.

comp_tmp_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

2023-11-23 03:44 UTC, merged