refactor ma_convproc_intr
eagles-project/e3sm_mam4_refactor pull request #29
Opened 2022-10-26 22:18 UTC by tangshuaiqi

`history_aero_prevap_resusp `and `history_aero_prevap_resusp` are always true in this subroutine. remove it.

separate the calculation of deep and shallow convective processing tendency as a subroutine `update_qnew_ptend `and also apply it to processing preparation.

2022-10-26 23:57 UTC, singhbalwinder requested changes
Nice job of factoring out the update ptend subroutine! I left some very minor comments and suggested to add short description of the new subroutine.

2022-10-26 23:57 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/aero_model.F90
> +            ptend, aerdepwetis                                ) ! inout
Thanks for re-arranging the input into "ins" and "outs"

2022-10-26 23:57 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/modal_aero_convproc.F90
> +  hund_ovr_g = 100.0_r8/gravit
Can this be a parameter? I am not sure if gravit is declared as a parameter or not.

2022-10-26 23:57 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/modal_aero_convproc.F90
> +
Maybe add a line or two to describe this subroutine.

2022-10-27 01:46 UTC, tangshuaiqi commented on components/eam/src/chemistry/modal_aero/modal_aero_convproc.F90
> +  hund_ovr_g = 100.0_r8/gravit
I found that in components/eam/src/control/physconst.F90:
`real(r8), public           :: gravit       = shr_const_g`
and another line that may update `gravit `from namelist:
` namelist /physconst_nl/  cpwv, gravit, mwdry, mwh2o, rearth, sday, tmelt, tms_orocnst, tms_z0fac, omega`
So gravit is not a parameter and this cannot be set as parameter.

2022-10-27 01:48 UTC, tangshuaiqi commented on components/eam/src/chemistry/modal_aero/modal_aero_convproc.F90
> +
will add

2022-10-27 18:11 UTC, singhbalwinder approved these changes

2022-10-27 18:12 UTC, singhbalwinder commented
Thanks, @tangshuaiqi! Please run the tests and merge this PR if all the tests pass.

2022-10-27 19:58 UTC, tangshuaiqi commented
All tests pass. merge into maint-2.0-refactor

```
comp_testall_convproc_intr_mam4_org_v2_baselines: 5 tests
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
```

2022-10-27 19:59 UTC, merged