Refactor mam_amicphys_1subarea_cloudy/clear
eagles-project/e3sm_mam4_refactor pull request #56
Opened 2023-01-06 18:04 UTC by huiwanpnnl

The original MAM microphysics code had two bottom-level driver subroutines, `mam_amicphys_1subarea_cloudy` and `mam_amicphys_1subarea_clear`, in which the various microphysics processes (e.g., nucleation, renaming) were called. These two subroutines were very (>80%) similar, although some calculations were done only for the cloudy subarea and some others were done only for the clear subarea.

In this PR, I have
- merged the two subroutines into one, now called `mam_amicphys_1subarea`,
- simplified the logic (e.g., the use of logical variables, if-statements, and temporary variables),
- did the usual clean-up (e.g., removed unused variables, added comments, etc.)

Note that the new subroutine `mam_amicphys_1subarea` is temporarily placed in a separate file `1subarea.F90` and imported into `modal_aero_amicphys.F90` using
```
#include "1subarea.F90"
```
This was because `modal_aero_amicphys.F90` is a very large file and I wanted to avoid potential conflict between different refactoring efforts.

2023-01-10 18:38 UTC, singhbalwinder requested changes
Very nice refactor! The comments you added are very useful in following the code and code itself is refactored in a way that it is easy to read. Thanks for cleaning up the code!
I have left some very minor comments.

2023-01-10 18:38 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +! qgas3, qaer3, qaercw3, qnum3, qnumcw3 are the current incoming TMRs
Maybe add units of TMRs in this comment.

2023-01-10 18:38 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +!--------------------------------------------------------------------------------
Very nice summary!

2023-01-10 18:38 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +                                 nstep,      lchnk,      i,        k,        &
If it is not too much work, would you please change `i` to `icol` (or `ii`) and `k` to `kk`?

2023-01-10 18:38 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +   use modal_aero_data,   only: n_mode=>ntot_amode
is `max_mode` different from `ntot_amode` for MAM4?

2023-01-10 18:38 UTC, singhbalwinder commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +         if (newnuc_h2so4_conc_optaa == 11) then
`newnuc_h2so4_conc_optaa` is set to 2 in amicphys_control. I don't think it changes during the simulation. We can make it a parameter and remove codes where it is not 2.

2023-01-12 22:38 UTC, huiwanpnnl commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +!--------------------------------------------------------------------------------
Thanks!

2023-01-12 22:43 UTC, huiwanpnnl commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +! qgas3, qaer3, qaercw3, qnum3, qnumcw3 are the current incoming TMRs
The different TMRs have different units. I've now noted them later in the code (when the variables are declared). See [1f569df](https://github.com/eagles-project/e3sm_mam4_refactor/pull/56/commits/1f569df66de852defc89e8557d348070b0529eb6).

2023-01-12 22:55 UTC, huiwanpnnl commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +                                 nstep,      lchnk,      i,        k,        &
Ah, sorry for overlooking this. Updated in [68924d3](https://github.com/eagles-project/e3sm_mam4_refactor/pull/56/commits/68924d3b748cd9184276ae82558254c7ddff56a1).

2023-01-12 23:07 UTC, huiwanpnnl commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +   use modal_aero_data,   only: n_mode=>ntot_amode
I printed their values and got 
```
max_mode = 5
ntot_amode = 4
```

2023-01-12 23:16 UTC, huiwanpnnl commented on components/eam/src/chemistry/modal_aero/1subarea.F90
> +         if (newnuc_h2so4_conc_optaa == 11) then
Good point. `newnuc_h2so4_conc_optaa` values other than 2 were probably used only in CAM and during the development of EAMv1. I've updated the code as suggested. See [925c581](https://github.com/eagles-project/e3sm_mam4_refactor/pull/56/commits/925c5814b7a401dc4ee965c783f626e091f24bda).

2023-01-13 14:41 UTC, huiwanpnnl commented
_Testing on Compy_

Commands used to run all tests:
```
cd /qfs/people/wanh895/codes/e3sm_mam4_refactor_amicphys_1subarea/
bash mam4_refactor_scripts/compare_baselines_all_tests.sh  \
     -b huiwanpnnl/refactor-amicphys-1subarea_rebased-20230106 \
     -t ALL_TESTS_refactor-amicphys-1subarea_rebased-20230106
```

Commands used to check the results:
```
cd /compyfs/wanh895/e3sm_scratch//ALL_TESTS_refactor-amicphys-1subarea_rebased-20230106
./cs.status.comp_ALL_TESTS_refactor-amicphys-1subarea_rebased-20230106_mam4_org_v2_baselines -s
```

The results were
```
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  DIFF SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel
```

2023-01-13 14:46 UTC, huiwanpnnl commented
If I understood it correctly, results from a year-long simulations do not match the baseline. 

The cprnc output in `/compyfs/wanh895/e3sm_scratch/ALL_TESTS_refactor-amicphys-1subarea_rebased-20230106/SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel.C.comp_ALL_TESTS_refactor-amicphys-1subarea_rebased-20230106_mam4_org_v2_baselines/SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel.C.comp_ALL_TESTS_refactor-amicphys-1subarea_rebased-20230106_mam4_org_v2_baselines.eam.h0.0001-12.nc.cprnc.out` reveals that there are 10 out of 416 variables showing differences. Those variables have the suffix `_sfgaex1`, but some other variables with the same suffix show no differences. 

I suspect I had a small bug related to the Fortran arrays used for history output. I'll investigate.

2023-01-13 18:00 UTC, singhbalwinder commented
Thanks, Hui for addressing the comments and testing. Typically, if the 1-year simulation is failing, it might fail for a 1-month or shorter run as well. I have put some notes [on confluence](https://eagles-project.atlassian.net/wiki/spaces/Computation/pages/1664253957/Tracking+down+non-BFB+Errors) which might be helpful in setting up a shorter simulation and tracking it down. Let me know if you have any questions on this.

2023-01-13 21:17 UTC, huiwanpnnl commented
Yes, I saw your very useful instructions - and will follow them to do my investigation. Thanks!

2023-01-24 17:23 UTC, huiwanpnnl commented
Hi @singhbalwinder, sorry for the delay in addressing the nonBFB issue and thanks again for your very helpful instructions on Confluence. My problem was indeed reproducible with 1-month runs and only in the diagnostics.

I resolved the nonBFB issue in [685afa2](https://github.com/eagles-project/e3sm_mam4_refactor/pull/56/commits/685afa254964baeb18cac50c9853923b19090d53). Here are the test results:

*Testing on Compy*

Commands used to run all tests:

```
bash mam4_refactor_scripts/compare_baselines_all_tests.sh \
     -b huiwanpnnl/refactor-amicphys-1subarea_rebased-20230106 \
     -t ALL_TESTS_refactor-amicphys-1subarea_revised-20230123
```

Commands used to check the results:

```
cd /compyfs/wanh895/e3sm_scratch//ALL_TESTS_refactor-amicphys-1subarea_revised-20230123
./cs.status.comp_ALL_TESTS_refactor-amicphys-1subarea_revised-20230123_mam4_org_v2_baselines -s
```

The results were
```
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel
```

2023-01-24 22:13 UTC, singhbalwinder commented
Thanks, Hui! I know sometimes it takes a lot of time to track these issues. Everything looks great! I will merge this PR.

2023-01-24 22:13 UTC, singhbalwinder approved these changes

2023-01-24 22:14 UTC, merged